
#workflow name
name: "Build & Deploy Bot"

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  build: 
    runs-on: self-hosted
    steps:
    - run: "yarn install --immutable --immutable-cache --check-cache"
    - run: "yarn run build"
  deploy:
    runs-on: self-hosted
    env:
      TOKEN: ${{secrets.TOKEN}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      INSTAGRAM_USERNAME: ${{secrets.INSTAGRAM_USERNAME}}
      INSTAGRAM_PASSWORD: ${{secrets.INSTAGRAM_PASSWORD}}
    steps:
      - run: "pm2 restart rplbot --update-env"
    
