
#workflow name
name: "Build & Deploy Bot"

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  build-and-deploy: 
    runs-on: self-hosted
    env:
      TOKEN: ${{secrets.TOKEN}}
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      MONGODB_URI: ${{secrets.MONGODB_URI}}
      INSTAGRAM_USERNAME: ${{secrets.INSTAGRAM_USERNAME}}
      INSTAGRAM_PASSWORD: ${{secrets.INSTAGRAM_PASSWORD}}
      REDIS_URL: ${{secrets.REDIS_URL}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Package
      run: "yarn install --immutable --immutable-cache --check-cache"
    - run: "yarn run build"
    - name: Deploy To Server
      run: "pm2 restart rplbot --update-env"
    
